### ISSUE TITLE
 ./lgcommander.py Network error

### ISSUE THREAD

**Issue by lukiifaz** [ubaransel/lgcommander#14]
Hello. 
Raspberry Pi 3B 
Raspbian stretch
Python 3.5.3 

Radndom erorr: 
pi@raspberrypi:~/lgcommander $ ./lgcommander.py
Lg TV not found

pi@raspberrypi:~/lgcommander $ ./lgcommander.py
Network error

pi@raspberrypi:~/lgcommander $ ./lgcommander.py
Traceback (most recent call last):
  File "./lgcommander.py", line 137, in <module>
    root = Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1880, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by ubaransel** [comment]
lgcommander.py needs X server.

**Comment by lukiifaz** [comment]
X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.41-v7+ armv7l Raspbian
Current Operating System: Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l
Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=0005e85a-07 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait splash plymouth.ignore-serial-consoles
Build Date: 18 October 2017  04:55:30PM
xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://www.debian.org/support)
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
p

**Comment by ubaransel** [comment]
if you run:
"env |grep -i display"
from a tty outside a desktop session you get nothing, because there is "no display name and no $DISPLAY environment variable"
but if you run
"env |grep -i display"
on a virtual terminal  while inside a desktop session you get something like
$ env|grep -i display
DISPLAY=:0.0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

**Comment by lukiifaz** [comment]
Ok 
I can`t use thist script via ssh :/ Thx for help.

**Comment by ypid** [comment]
@lukiifaz Maybe my fork works for you. I think I made X optional when you provide the session ID. https://github.com/ypid/lgcommander

**Comment by lukiifaz** [comment]
Thx ypid, work  perfect .
