### ISSUE TITLE
lgcommander works intermittent

### ISSUE THREAD

**Issue by noureddin212** [ubaransel/lgcommander#15]
Hello 
I do not know what is causing that but sometimes the script is not working 
I am running it on Pi3 on LG 2012 

pi@raspberrypi:~/domoticz/scripts/python $ ./lg_tv_on.py
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/python/lg.py", line 42, in <module>
    theSessionid = getSessionid()
  File "/home/pi/domoticz/scripts/python/lg.py", line 25, in getSessionid
    conn.request("POST", "/roap/api/auth", pairCmd, headers=headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

**Comment by ypid** [comment]
It pretty much says it on the last line. Check your network, the TV was not reachable. Maybe try a ping and similar commands.
